repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
      - id: pyupgrade
        args: ["--py38-plus"]

  - repo: "https://github.com/psf/black"
    rev: 23.7.0
    hooks:
      - id: black
        args: [--line-length=88]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.0.286'
    hooks:
      - id: ruff
        exclude: pie/recipes.py
        args: [--fix, --exit-non-zero-on-fix]


  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      # - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      # - id: fix-encoding-pragma
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/mgedmin/check-manifest
    rev: "0.49"
    hooks:
      - id: check-manifest
        stages: [manual]

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        name: 'detect-secrets'
        args: ['--exclude-files', '.*\.ipynb$', ]
      - id: detect-secrets
        name: 'detect-secrets-jupyter'
        args: ['--exclude-files', '.*[^i][^p][^y][^n][^b]$', '--exclude-lines', '"(hash|id|image/\w+)":.*', ]
